language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
# TODO: fix doctest freezing in Python 3.5

# command to install dependencies
install:
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py -q install

# setup different django versions
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11

# command to run tests
script:
  python django_orm_sugar.py
